### ISSUE TITLE
Error loading the model

### ISSUE THREAD

**Issue by hohoCode** [tanbro/allennlp-runmodel#1]
Thanks for the great tool.

However I cannot load the model. The error msg are shown below. 

Thanks.

**Comment by hohoCode** [comment]
Finally being able to install the tool but got the following error msg during model loading stage.

Traceback (most recent call last):
  File ".../lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File ".../lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".../lib/python3.6/concurrent/futures/process.py", line 272, in _queue_management_worker
    result_item = reader.recv()
  File "../lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'message

**Comment by tanbro** [comment]
@hohoCode Thank you for the issue!

it has been a long time since last update...

AllenNLP changes a lot, but this small project not.

So, would anyone commit a piece of codes to fix the problem?
